server:
  port: 3355
spring:
  application:
    name: config-client
  cloud:
    config:
      label: main
      name: config #配置文件的名称
      profile: main #配置文件的后缀，和上面的name搭配使用，会自动加上-，最终就是config-main.yml
      uri: http://localhost:3344
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka    # 单机版
config:
  info: "6546s54da"
